aliases:
  - "mctreasure"
  - "treasure"
  - "treasurechest"

placeholders:
  status:
    enabled: "&a☑"
    disabled: "&c☒"
    set: "&a☑"
    not-set: "&c☒"
    none: "&c☒"

  location:
    format: "&7%s&8, &7%d&8, &7%d&8, &7%d"
    not-set: "&c☒"

  cooldown:
    set: "&a%s"
    none: "&c☒"

  size:
    format: "&a%d"

  permission:
    format: "&a%s"
    none: "&c☒"

  particle:
    format: "&a%s"

  hologram:
    time-left: "&c%s"
    ready: "&a&lREADY TO OPEN&7!"

effect-particles:
  helix: "CRIT"
  heart: "FLAME"
  tornado: "BUBBLE"
  pulsar: "WITCH"
  sphere: "END_ROD"
  spiral: "END_ROD"
  phoenix: "END_ROD"