name: mc-Treasure
version: '1.0.9'
main: com.mongenscave.mctreasure.McTreasure
api-version: '1.18'
authors: [coma112]
softdepend: [DecentHolograms, PlaceholderAPI, FancyHolograms]
folia-supported: true